/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.plexus.infraestructure.web.controller;

import java.util.LinkedHashSet;

import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestParam;

import com.plexus.domain.model.in.AssetFileUploadRequest;
import com.plexus.domain.model.out.AssetFileUploadResponse;
import com.plexus.domain.model.out.AssetSearchResponse;

import io.github.resilience4j.ratelimiter.annotation.RateLimiter;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import reactor.core.publisher.Mono;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-09-15T10:38:49.797096500+02:00[Europe/Madrid]")
@Validated
@Tag(name = "asset", description = "the asset API")
public interface AssetApi {

    /**
     * GET /api/mgmt/1/assets/ : Allows searching (&amp; filtering) all the uploaded/registered assets.
     * Allows searching (&amp; filtering) all the uploaded/registered assets.
     *
     * @param uploadDateStart The start date for the range. (optional)
     * @param uploadDateEnd The end date for the range. (optional)
     * @param filename The filename expression for file filtering (regex). (optional)
     * @param filetype The file types for file filtering (one at a time). (optional)
     * @param sortDirection  (optional)
     * @return Returns a list of assets matching the specified criteria. (status code 200)
     *         or Malformed request. (status code 400)
     *         or An unexpected error occurred. (status code 500)
     */
    @GetMapping("/")
    @RateLimiter(name = "search-endpoint")
    @Operation(
            summary = "Allows searching (& filtering) all the uploaded/registered assets.",
            description = "Allows searching all the uploaded/registered assets by using all the given filters.",
            operationId = "getAssetsByFilter",
            responses = {
                    @ApiResponse(responseCode = "200", description = "Returns a list of assets matching the specified criteria.",
                            content = @Content(mediaType = "application/json",
                                    schema = @Schema(type = "array", implementation = com.plexus.domain.model.out.AssetSearchResponse.class))),
                    @ApiResponse(responseCode = "400", description = "Malformed request.", content = @Content()),
                    @ApiResponse(responseCode = "500", description = "An unexpected error occurred.", content = @Content())
            }
    )
    public Mono<ResponseEntity<LinkedHashSet<AssetSearchResponse>>> search(
            @Parameter(description = "The start date for the range.") @RequestParam(required = false) String uploadDateStart, 
            @Parameter(description = "The end date for the range.") @RequestParam(required = false) String uploadDateEnd,
            @Parameter(description = "The filename expression for file filtering (regex).") @RequestParam(required = false) String filename,
            @Parameter(description = "The file types for file filtering (one at a time).") @RequestParam(required = false) String filetype,
            @Parameter(description = "Sort direction") @RequestParam(required = false) String sortDirection
    );


    /**
     * POST /api/mgmt/1/assets/actions/upload : Performs an upload of the requested asset file.
     * Performs an upload of the requested asset file.
     *
     * @param assetFileUploadRequest  (required)
     * @return The operation was accepted by the backend. (status code 202)
     *         or An unexpected error occurred. (status code 500)
     */
    @PostMapping("/actions/upload")
    @Operation(
            summary = "Performs an upload of the requested asset file.",
            description = "Performs an upload of the requested asset file. It communicates with the asset service to upload the file, but it ends without waiting for the file to be uploaded.",
            operationId = "uploadAssetFile",
            responses = {
                    @ApiResponse(responseCode = "202", description = "The operation was accepted by the backend.",
                            content = @Content(mediaType = "application/json",
                                    schema = @Schema(implementation = com.plexus.domain.model.out.AssetFileUploadResponse.class))),
                    @ApiResponse(responseCode = "400", description = "Malformed request.", content = @Content()),
                    @ApiResponse(responseCode = "500", description = "An unexpected error occurred.", content = @Content())
            }
    )
    public Mono<ResponseEntity<AssetFileUploadResponse>> upload(@RequestBody AssetFileUploadRequest request);

}
